modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Starcage"

description='''
Template
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="meliorat.mixins.json"

#[features.${mod_id}]
#openGLVersion="[3.2,)"

#[modproperties."meliorat"]
#catalogueImageIcon = "assets/logo.png"